name: GenBuckets
main: com.reliableplugins.genbucket.GenBucket
version: ${project.version}
authors: [Rages, Driftay]
api-version: 1.13
softdepend:
  - Factions
  - WorldGuard
  - MassiveCore
  - CombatLogX
commands:
  genbucket:
    description: "The most optimized GenBucket plugin."
    usage: "/genbucket help"
    aliases: [gen, gb]